// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package orgusersdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultAdminRole = `-- name: CreateDefaultAdminRole :one
INSERT INTO roles (organisation_id, name, description, is_system, created_at, updated_at)
VALUES ($1, 'Admin', 'Administrator with full access', true, NOW(), NOW())
RETURNING id, organisation_id, name, description, is_system, created_at, updated_at
`

func (q *Queries) CreateDefaultAdminRole(ctx context.Context, organisationID uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, createDefaultAdminRole, organisationID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrgUser = `-- name: CreateOrgUser :one
INSERT INTO users (organisation_id, email, password_hash, name, role, role_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, true, NOW(), NOW())
RETURNING id, organisation_id, email, name, role, role_id, is_active, created_at
`

type CreateOrgUserParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Name           string      `json:"name"`
	Role           string      `json:"role"`
	RoleID         pgtype.UUID `json:"role_id"`
}

type CreateOrgUserRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	RoleID         pgtype.UUID        `json:"role_id"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrgUser(ctx context.Context, arg CreateOrgUserParams) (CreateOrgUserRow, error) {
	row := q.db.QueryRow(ctx, createOrgUser,
		arg.OrganisationID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.RoleID,
	)
	var i CreateOrgUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgUserCount = `-- name: GetOrgUserCount :one
SELECT COUNT(*)::bigint FROM users WHERE organisation_id = $1
`

func (q *Queries) GetOrgUserCount(ctx context.Context, organisationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgUserCount, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, organisation_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE id = $1 AND organisation_id = $2
`

type GetRoleByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.ID, arg.OrganisationID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, organisation_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE organisation_id = $1 AND name = $2
`

type GetRoleByNameParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.OrganisationID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, organisation_id, email, name, role, is_active, role_id, created_at
FROM users
WHERE organisation_id = $1
ORDER BY created_at DESC
`

type ListUsersByOrgRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	RoleID         pgtype.UUID        `json:"role_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersByOrg(ctx context.Context, organisationID uuid.UUID) ([]ListUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrgRow
	for rows.Next() {
		var i ListUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.RoleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1 AND organisation_id = $3
RETURNING id, organisation_id, email, name, role, role_id, is_active, updated_at
`

type SetUserStatusParams struct {
	ID             uuid.UUID `json:"id"`
	IsActive       bool      `json:"is_active"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

type SetUserStatusRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	RoleID         pgtype.UUID        `json:"role_id"`
	IsActive       bool               `json:"is_active"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (SetUserStatusRow, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.IsActive, arg.OrganisationID)
	var i SetUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RoleID,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const userEmailExistsInOrg = `-- name: UserEmailExistsInOrg :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND organisation_id = $2)::boolean
`

type UserEmailExistsInOrgParams struct {
	Email          string    `json:"email"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) UserEmailExistsInOrg(ctx context.Context, arg UserEmailExistsInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExistsInOrg, arg.Email, arg.OrganisationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
