// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrgUser = `-- name: CreateOrgUser :one
INSERT INTO users (organisation_id, email, password_hash, name, role, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, true, NOW(), NOW())
RETURNING id, organisation_id, email, name, role, is_active, created_at
`

type CreateOrgUserParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Email          string    `json:"email"`
	PasswordHash   string    `json:"password_hash"`
	Name           string    `json:"name"`
	Role           string    `json:"role"`
}

type CreateOrgUserRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrgUser(ctx context.Context, arg CreateOrgUserParams) (CreateOrgUserRow, error) {
	row := q.db.QueryRow(ctx, createOrgUser,
		arg.OrganisationID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i CreateOrgUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, organisation_id, email, name, role, is_active, created_at
FROM users
WHERE organisation_id = $1
ORDER BY created_at DESC
`

type ListUsersByOrgRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersByOrg(ctx context.Context, organisationID uuid.UUID) ([]ListUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrgRow
	for rows.Next() {
		var i ListUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organisation_id, email, name, role, is_active, updated_at
`

type SetUserStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

type SetUserStatusRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (SetUserStatusRow, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.IsActive)
	var i SetUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const userEmailExistsInOrg = `-- name: UserEmailExistsInOrg :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND organisation_id = $2)::boolean
`

type UserEmailExistsInOrgParams struct {
	Email          string    `json:"email"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) UserEmailExistsInOrg(ctx context.Context, arg UserEmailExistsInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExistsInOrg, arg.Email, arg.OrganisationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
