// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package templatesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    organisation_id, name, html_content, is_default, thumbnail_url, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, organisation_id, name, html_content, is_default, thumbnail_url, created_by, created_at, updated_at
`

type CreateTemplateParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Name           string      `json:"name"`
	HtmlContent    string      `json:"html_content"`
	IsDefault      bool        `json:"is_default"`
	ThumbnailUrl   *string     `json:"thumbnail_url"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.OrganisationID,
		arg.Name,
		arg.HtmlContent,
		arg.IsDefault,
		arg.ThumbnailUrl,
		arg.CreatedBy,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.HtmlContent,
		&i.IsDefault,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1 AND organisation_id = $2
`

type DeleteTemplateParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.OrganisationID)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, organisation_id, name, html_content, is_default, thumbnail_url, created_by, created_at, updated_at
FROM templates
WHERE id = $1 AND organisation_id = $2
`

type GetTemplateByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.OrganisationID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.HtmlContent,
		&i.IsDefault,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplates = `-- name: GetTemplates :many
SELECT id, organisation_id, name, html_content, is_default, thumbnail_url, created_by, created_at, updated_at
FROM templates
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTemplates(ctx context.Context, organisationID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, getTemplates, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.HtmlContent,
			&i.IsDefault,
			&i.ThumbnailUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    name = COALESCE($3, name),
    html_content = COALESCE($4, html_content),
    is_default = COALESCE($5, is_default),
    thumbnail_url = COALESCE($6, thumbnail_url),
    updated_at = NOW()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, name, html_content, is_default, thumbnail_url, created_by, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           *string   `json:"name"`
	HtmlContent    *string   `json:"html_content"`
	IsDefault      *bool     `json:"is_default"`
	ThumbnailUrl   *string   `json:"thumbnail_url"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.HtmlContent,
		arg.IsDefault,
		arg.ThumbnailUrl,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.HtmlContent,
		&i.IsDefault,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
