// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package rolesdb

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (organisation_id, name, description, is_system, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, organisation_id, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	IsSystem       bool      `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrganisationID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1 AND organisation_id = $2 AND is_system = false
`

type DeleteRoleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.OrganisationID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, organisation_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE id = $1 AND organisation_id = $2
`

type GetRoleByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.ID, arg.OrganisationID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, organisation_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE organisation_id = $1 AND name = $2
`

type GetRoleByNameParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.OrganisationID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, organisation_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoles(ctx context.Context, organisationID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $3, description = $4, updated_at = NOW()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Description,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
