// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package authdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSuperAdmin = `-- name: CreateSuperAdmin :one
INSERT INTO super_admins (email, password_hash, role, is_active, created_at, updated_at)
VALUES ($1, $2, $3, true, NOW(), NOW())
RETURNING id, email, role, created_at
`

type CreateSuperAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateSuperAdminRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSuperAdmin(ctx context.Context, arg CreateSuperAdminParams) (CreateSuperAdminRow, error) {
	row := q.db.QueryRow(ctx, createSuperAdmin, arg.Email, arg.PasswordHash, arg.Role)
	var i CreateSuperAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createSuperRefreshToken = `-- name: CreateSuperRefreshToken :exec
INSERT INTO super_refresh_tokens (super_admin_id, token_hash, expires_at, ip_address, user_agent, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type CreateSuperRefreshTokenParams struct {
	SuperAdminID uuid.UUID          `json:"super_admin_id"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
}

func (q *Queries) CreateSuperRefreshToken(ctx context.Context, arg CreateSuperRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createSuperRefreshToken,
		arg.SuperAdminID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const getSuperAdminByEmail = `-- name: GetSuperAdminByEmail :one
SELECT id, email, password_hash, role, is_active, failed_attempts, locked_until, last_login_at, created_at, updated_at
FROM super_admins
WHERE email = $1
`

func (q *Queries) GetSuperAdminByEmail(ctx context.Context, email string) (SuperAdmin, error) {
	row := q.db.QueryRow(ctx, getSuperAdminByEmail, email)
	var i SuperAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuperAdminByID = `-- name: GetSuperAdminByID :one
SELECT id, email, password_hash, role, is_active, failed_attempts, locked_until, last_login_at, created_at, updated_at
FROM super_admins
WHERE id = $1
`

func (q *Queries) GetSuperAdminByID(ctx context.Context, id uuid.UUID) (SuperAdmin, error) {
	row := q.db.QueryRow(ctx, getSuperAdminByID, id)
	var i SuperAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE super_admins
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE WHEN failed_attempts >= 4 THEN NOW() + INTERVAL '15 minutes' ELSE NULL END
WHERE id = $1
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedAttempts, id)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE super_admins
SET failed_attempts = 0, locked_until = NULL, last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const revokeAllSuperRefreshTokens = `-- name: RevokeAllSuperRefreshTokens :exec
UPDATE super_refresh_tokens
SET revoked_at = NOW()
WHERE super_admin_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSuperRefreshTokens(ctx context.Context, superAdminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSuperRefreshTokens, superAdminID)
	return err
}

const superAdminEmailExists = `-- name: SuperAdminEmailExists :one
SELECT EXISTS(SELECT 1 FROM super_admins WHERE email = $1)::boolean
`

func (q *Queries) SuperAdminEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, superAdminEmailExists, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
