// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package invoicesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelInvoice = `-- name: CancelInvoice :one
UPDATE invoices
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, customer_id, session_id, invoice_number, status, issued_date, due_date, subtotal, tax_amount, discount_amount, total, currency, notes, terms, template_id, created_by, sent_at, paid_at, created_at, updated_at
`

type CancelInvoiceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) CancelInvoice(ctx context.Context, arg CancelInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, cancelInvoice, arg.ID, arg.OrganisationID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CustomerID,
		&i.SessionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.IssuedDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.Currency,
		&i.Notes,
		&i.Terms,
		&i.TemplateID,
		&i.CreatedBy,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    organisation_id, customer_id, session_id, invoice_number, status, issued_date, due_date,
    subtotal, tax_amount, discount_amount, total, currency, notes, terms, template_id, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, NOW(), NOW()
)
RETURNING id, organisation_id, customer_id, session_id, invoice_number, status, issued_date, due_date, subtotal, tax_amount, discount_amount, total, currency, notes, terms, template_id, created_by, sent_at, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	OrganisationID uuid.UUID      `json:"organisation_id"`
	CustomerID     uuid.UUID      `json:"customer_id"`
	SessionID      uuid.UUID      `json:"session_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Status         string         `json:"status"`
	IssuedDate     pgtype.Date    `json:"issued_date"`
	DueDate        pgtype.Date    `json:"due_date"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Total          pgtype.Numeric `json:"total"`
	Currency       string         `json:"currency"`
	Notes          *string        `json:"notes"`
	Terms          *string        `json:"terms"`
	TemplateID     pgtype.UUID    `json:"template_id"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganisationID,
		arg.CustomerID,
		arg.SessionID,
		arg.InvoiceNumber,
		arg.Status,
		arg.IssuedDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.Total,
		arg.Currency,
		arg.Notes,
		arg.Terms,
		arg.TemplateID,
		arg.CreatedBy,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CustomerID,
		&i.SessionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.IssuedDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.Currency,
		&i.Notes,
		&i.Terms,
		&i.TemplateID,
		&i.CreatedBy,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    invoice_id, service_id, description, quantity, unit_price, tax_rate, tax_amount, line_total, sort_order, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
RETURNING id, invoice_id, service_id, description, quantity, unit_price, tax_rate, tax_amount, line_total, sort_order, created_at
`

type CreateInvoiceItemParams struct {
	InvoiceID   uuid.UUID      `json:"invoice_id"`
	ServiceID   pgtype.UUID    `json:"service_id"`
	Description string         `json:"description"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	TaxAmount   pgtype.Numeric `json:"tax_amount"`
	LineTotal   pgtype.Numeric `json:"line_total"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.ServiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxRate,
		arg.TaxAmount,
		arg.LineTotal,
		arg.SortOrder,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ServiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.TaxRate,
		&i.TaxAmount,
		&i.LineTotal,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, organisation_id, customer_id, session_id, invoice_number, status, issued_date, due_date, subtotal, tax_amount, discount_amount, total, currency, notes, terms, template_id, created_by, sent_at, paid_at, created_at, updated_at
FROM invoices
WHERE id = $1 AND organisation_id = $2
`

type GetInvoiceByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.OrganisationID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CustomerID,
		&i.SessionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.IssuedDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.Currency,
		&i.Notes,
		&i.Terms,
		&i.TemplateID,
		&i.CreatedBy,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceItems = `-- name: GetInvoiceItems :many
SELECT id, invoice_id, service_id, description, quantity, unit_price, tax_rate, tax_amount, line_total, sort_order, created_at
FROM invoice_items
WHERE invoice_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) GetInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, getInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ServiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxRate,
			&i.TaxAmount,
			&i.LineTotal,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoices = `-- name: GetInvoices :many
SELECT id, organisation_id, customer_id, session_id, invoice_number, status, issued_date, due_date, subtotal, tax_amount, discount_amount, total, currency, notes, terms, template_id, created_by, sent_at, paid_at, created_at, updated_at
FROM invoices
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvoices(ctx context.Context, organisationID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, getInvoices, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CustomerID,
			&i.SessionID,
			&i.InvoiceNumber,
			&i.Status,
			&i.IssuedDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.Total,
			&i.Currency,
			&i.Notes,
			&i.Terms,
			&i.TemplateID,
			&i.CreatedBy,
			&i.SentAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
