// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package paymentsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    organisation_id, invoice_id, amount, method, reference, notes, payment_date, recorded_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
RETURNING id, organisation_id, invoice_id, amount, method, reference, notes, payment_date, recorded_by, created_at
`

type CreatePaymentParams struct {
	OrganisationID uuid.UUID      `json:"organisation_id"`
	InvoiceID      uuid.UUID      `json:"invoice_id"`
	Amount         pgtype.Numeric `json:"amount"`
	Method         string         `json:"method"`
	Reference      *string        `json:"reference"`
	Notes          *string        `json:"notes"`
	PaymentDate    pgtype.Date    `json:"payment_date"`
	RecordedBy     pgtype.UUID    `json:"recorded_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrganisationID,
		arg.InvoiceID,
		arg.Amount,
		arg.Method,
		arg.Reference,
		arg.Notes,
		arg.PaymentDate,
		arg.RecordedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.InvoiceID,
		&i.Amount,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.PaymentDate,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments
WHERE id = $1 AND organisation_id = $2
`

type DeletePaymentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) DeletePayment(ctx context.Context, arg DeletePaymentParams) error {
	_, err := q.db.Exec(ctx, deletePayment, arg.ID, arg.OrganisationID)
	return err
}

const getPaymentsByInvoice = `-- name: GetPaymentsByInvoice :many
SELECT id, organisation_id, invoice_id, amount, method, reference, notes, payment_date, recorded_by, created_at
FROM payments
WHERE invoice_id = $1 AND organisation_id = $2
ORDER BY created_at DESC
`

type GetPaymentsByInvoiceParams struct {
	InvoiceID      uuid.UUID `json:"invoice_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetPaymentsByInvoice(ctx context.Context, arg GetPaymentsByInvoiceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByInvoice, arg.InvoiceID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.InvoiceID,
			&i.Amount,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.PaymentDate,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByOrg = `-- name: GetPaymentsByOrg :many
SELECT id, organisation_id, invoice_id, amount, method, reference, notes, payment_date, recorded_by, created_at
FROM payments
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsByOrg(ctx context.Context, organisationID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.InvoiceID,
			&i.Amount,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.PaymentDate,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
