// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package orgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSubscriptions = `-- name: CancelActiveSubscriptions :exec
UPDATE organisation_subscriptions
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE organisation_id = $1 AND status = 'active'
`

func (q *Queries) CancelActiveSubscriptions(ctx context.Context, organisationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSubscriptions, organisationID)
	return err
}

const countOrganisations = `-- name: CountOrganisations :one
SELECT COUNT(*)::int FROM organisations
`

func (q *Queries) CountOrganisations(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOrganisations)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (name, slug, email, phone, address, status, created_by_super_admin_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'active', $6, NOW(), NOW())
RETURNING id, name, slug, email, created_at
`

type CreateOrganisationParams struct {
	Name                  string      `json:"name"`
	Slug                  string      `json:"slug"`
	Email                 *string     `json:"email"`
	Phone                 *string     `json:"phone"`
	Address               *string     `json:"address"`
	CreatedBySuperAdminID pgtype.UUID `json:"created_by_super_admin_id"`
}

type CreateOrganisationRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Email     *string            `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (CreateOrganisationRow, error) {
	row := q.db.QueryRow(ctx, createOrganisation,
		arg.Name,
		arg.Slug,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.CreatedBySuperAdminID,
	)
	var i CreateOrganisationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO organisation_subscriptions 
    (organisation_id, plan_id, status, current_period_start, current_period_end, created_at, updated_at)
VALUES ($1, $2, 'active', NOW(), NOW() + INTERVAL '100 years', NOW(), NOW())
RETURNING id
`

type CreateSubscriptionParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	PlanID         uuid.UUID `json:"plan_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.OrganisationID, arg.PlanID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUnlimitedPlan = `-- name: CreateUnlimitedPlan :one
INSERT INTO plans (name, price_monthly, price_yearly, max_users, max_customers, 
    max_invoices_per_month, max_storage_mb, whatsapp_enabled, custom_templates, 
    api_access, is_active, created_at, updated_at)
VALUES ('Unlimited', 0, 0, 999999, 999999, 999999, 999999, true, true, true, true, NOW(), NOW())
RETURNING id
`

func (q *Queries) CreateUnlimitedPlan(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUnlimitedPlan)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT p.name AS plan_name, os.status, os.current_period_end
FROM organisation_subscriptions os
JOIN plans p ON p.id = os.plan_id
WHERE os.organisation_id = $1 AND os.status = 'active'
ORDER BY os.created_at DESC
LIMIT 1
`

type GetActiveSubscriptionRow struct {
	PlanName         string             `json:"plan_name"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, organisationID uuid.UUID) (GetActiveSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, organisationID)
	var i GetActiveSubscriptionRow
	err := row.Scan(&i.PlanName, &i.Status, &i.CurrentPeriodEnd)
	return i, err
}

const getOrganisationByID = `-- name: GetOrganisationByID :one
SELECT id, name, slug, email, phone, address, status, created_at, updated_at
FROM organisations
WHERE id = $1
`

type GetOrganisationByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	Address   *string            `json:"address"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganisationByID(ctx context.Context, id uuid.UUID) (GetOrganisationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganisationByID, id)
	var i GetOrganisationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id FROM plans WHERE id = $1 AND is_active = true
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	err := row.Scan(&id)
	return id, err
}

const getUnlimitedPlan = `-- name: GetUnlimitedPlan :one
SELECT id FROM plans WHERE name = 'Unlimited' LIMIT 1
`

func (q *Queries) GetUnlimitedPlan(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUnlimitedPlan)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listOrganisations = `-- name: ListOrganisations :many
SELECT id, name, slug, email, phone, status, created_at
FROM organisations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrganisationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrganisationsRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrganisations(ctx context.Context, arg ListOrganisationsParams) ([]ListOrganisationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganisations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganisationsRow
	for rows.Next() {
		var i ListOrganisationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgExists = `-- name: OrgExists :one
SELECT EXISTS(SELECT 1 FROM organisations WHERE id = $1)::boolean
`

func (q *Queries) OrgExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, orgExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const orgSlugExists = `-- name: OrgSlugExists :one
SELECT EXISTS(SELECT 1 FROM organisations WHERE slug = $1)::boolean
`

func (q *Queries) OrgSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, orgSlugExists, slug)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
