// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package reportsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerInvoiceHistory = `-- name: GetCustomerInvoiceHistory :many
SELECT
    i.id, i.invoice_number, i.status, i.issued_date, i.due_date,
    i.subtotal, i.tax_amount, i.total, i.currency, i.created_at
FROM invoices i
WHERE i.organisation_id = $1
  AND i.customer_id = $2
ORDER BY i.created_at DESC
`

type GetCustomerInvoiceHistoryParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	CustomerID     uuid.UUID `json:"customer_id"`
}

type GetCustomerInvoiceHistoryRow struct {
	ID            uuid.UUID          `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	IssuedDate    pgtype.Date        `json:"issued_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	Total         pgtype.Numeric     `json:"total"`
	Currency      string             `json:"currency"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCustomerInvoiceHistory(ctx context.Context, arg GetCustomerInvoiceHistoryParams) ([]GetCustomerInvoiceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getCustomerInvoiceHistory, arg.OrganisationID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerInvoiceHistoryRow
	for rows.Next() {
		var i GetCustomerInvoiceHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.Status,
			&i.IssuedDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyReport = `-- name: GetDailyReport :one
SELECT
    COUNT(i.id)::int                          AS total_invoices,
    COALESCE(SUM(i.total), 0)::numeric        AS total_revenue,
    COALESCE(SUM(i.tax_amount), 0)::numeric   AS total_tax,
    COUNT(CASE WHEN i.status = 'paid' THEN 1 END)::int     AS paid_count,
    COUNT(CASE WHEN i.status = 'pending' THEN 1 END)::int  AS pending_count,
    COUNT(CASE WHEN i.status = 'cancelled' THEN 1 END)::int AS cancelled_count
FROM invoices i
WHERE i.organisation_id = $1
  AND i.issued_date = $2::date
`

type GetDailyReportParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Column2        pgtype.Date `json:"column_2"`
}

type GetDailyReportRow struct {
	TotalInvoices  int32          `json:"total_invoices"`
	TotalRevenue   pgtype.Numeric `json:"total_revenue"`
	TotalTax       pgtype.Numeric `json:"total_tax"`
	PaidCount      int32          `json:"paid_count"`
	PendingCount   int32          `json:"pending_count"`
	CancelledCount int32          `json:"cancelled_count"`
}

func (q *Queries) GetDailyReport(ctx context.Context, arg GetDailyReportParams) (GetDailyReportRow, error) {
	row := q.db.QueryRow(ctx, getDailyReport, arg.OrganisationID, arg.Column2)
	var i GetDailyReportRow
	err := row.Scan(
		&i.TotalInvoices,
		&i.TotalRevenue,
		&i.TotalTax,
		&i.PaidCount,
		&i.PendingCount,
		&i.CancelledCount,
	)
	return i, err
}

const getMonthlyReport = `-- name: GetMonthlyReport :one
SELECT
    COUNT(i.id)::int                          AS total_invoices,
    COALESCE(SUM(i.total), 0)::numeric        AS total_revenue,
    COALESCE(SUM(i.tax_amount), 0)::numeric   AS total_tax,
    COUNT(CASE WHEN i.status = 'paid' THEN 1 END)::int     AS paid_count,
    COUNT(CASE WHEN i.status = 'pending' THEN 1 END)::int  AS pending_count,
    COUNT(CASE WHEN i.status = 'cancelled' THEN 1 END)::int AS cancelled_count
FROM invoices i
WHERE i.organisation_id = $1
  AND i.issued_date >= $2::date
  AND i.issued_date <= $3::date
`

type GetMonthlyReportParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Column2        pgtype.Date `json:"column_2"`
	Column3        pgtype.Date `json:"column_3"`
}

type GetMonthlyReportRow struct {
	TotalInvoices  int32          `json:"total_invoices"`
	TotalRevenue   pgtype.Numeric `json:"total_revenue"`
	TotalTax       pgtype.Numeric `json:"total_tax"`
	PaidCount      int32          `json:"paid_count"`
	PendingCount   int32          `json:"pending_count"`
	CancelledCount int32          `json:"cancelled_count"`
}

func (q *Queries) GetMonthlyReport(ctx context.Context, arg GetMonthlyReportParams) (GetMonthlyReportRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyReport, arg.OrganisationID, arg.Column2, arg.Column3)
	var i GetMonthlyReportRow
	err := row.Scan(
		&i.TotalInvoices,
		&i.TotalRevenue,
		&i.TotalTax,
		&i.PaidCount,
		&i.PendingCount,
		&i.CancelledCount,
	)
	return i, err
}

const getRevenueSummary = `-- name: GetRevenueSummary :many
SELECT
    DATE_TRUNC('month', i.issued_date)::date AS month,
    COUNT(i.id)::int                         AS total_invoices,
    COALESCE(SUM(i.total), 0)::numeric       AS total_revenue
FROM invoices i
WHERE i.organisation_id = $1
  AND i.issued_date >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', i.issued_date)
ORDER BY month ASC
`

type GetRevenueSummaryRow struct {
	Month         pgtype.Date    `json:"month"`
	TotalInvoices int32          `json:"total_invoices"`
	TotalRevenue  pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetRevenueSummary(ctx context.Context, organisationID uuid.UUID) ([]GetRevenueSummaryRow, error) {
	rows, err := q.db.Query(ctx, getRevenueSummary, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueSummaryRow
	for rows.Next() {
		var i GetRevenueSummaryRow
		if err := rows.Scan(&i.Month, &i.TotalInvoices, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
