// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package servicesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    organisation_id, name, description, unit_price, tax_rate, unit, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, organisation_id, name, description, unit_price, tax_rate, unit, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	OrganisationID uuid.UUID      `json:"organisation_id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	TaxRate        pgtype.Numeric `json:"tax_rate"`
	Unit           string         `json:"unit"`
	IsActive       bool           `json:"is_active"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OrganisationID,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.TaxRate,
		arg.Unit,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1 AND organisation_id = $2
`

type DeleteServiceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.Exec(ctx, deleteService, arg.ID, arg.OrganisationID)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, organisation_id, name, description, unit_price, tax_rate, unit, is_active, created_at, updated_at
FROM services
WHERE id = $1 AND organisation_id = $2
`

type GetServiceByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.OrganisationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServices = `-- name: GetServices :many
SELECT id, organisation_id, name, description, unit_price, tax_rate, unit, is_active, created_at, updated_at
FROM services
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetServices(ctx context.Context, organisationID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServices, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.TaxRate,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    unit_price = COALESCE($5, unit_price),
    tax_rate = COALESCE($6, tax_rate),
    unit = COALESCE($7, unit),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, name, description, unit_price, tax_rate, unit, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	ID             uuid.UUID      `json:"id"`
	OrganisationID uuid.UUID      `json:"organisation_id"`
	Name           *string        `json:"name"`
	Description    *string        `json:"description"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	TaxRate        pgtype.Numeric `json:"tax_rate"`
	Unit           *string        `json:"unit"`
	IsActive       *bool          `json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.TaxRate,
		arg.Unit,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
