// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package whatsappdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWhatsappLog = `-- name: CreateWhatsappLog :one
INSERT INTO whatsapp_logs (
    organisation_id, invoice_id, recipient_phone, message, status, error_message, sent_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id, organisation_id, invoice_id, recipient_phone, message, status, error_message, sent_at, created_at
`

type CreateWhatsappLogParams struct {
	OrganisationID uuid.UUID          `json:"organisation_id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	RecipientPhone string             `json:"recipient_phone"`
	Message        string             `json:"message"`
	Status         string             `json:"status"`
	ErrorMessage   *string            `json:"error_message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) CreateWhatsappLog(ctx context.Context, arg CreateWhatsappLogParams) (WhatsappLog, error) {
	row := q.db.QueryRow(ctx, createWhatsappLog,
		arg.OrganisationID,
		arg.InvoiceID,
		arg.RecipientPhone,
		arg.Message,
		arg.Status,
		arg.ErrorMessage,
		arg.SentAt,
	)
	var i WhatsappLog
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.InvoiceID,
		&i.RecipientPhone,
		&i.Message,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWhatsappLogs = `-- name: GetWhatsappLogs :many
SELECT id, organisation_id, invoice_id, recipient_phone, message, status, error_message, sent_at, created_at
FROM whatsapp_logs
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWhatsappLogs(ctx context.Context, organisationID uuid.UUID) ([]WhatsappLog, error) {
	rows, err := q.db.Query(ctx, getWhatsappLogs, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappLog
	for rows.Next() {
		var i WhatsappLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.InvoiceID,
			&i.RecipientPhone,
			&i.Message,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
