// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package settingsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSettings = `-- name: GetSettings :one
SELECT id, organisation_id, business_name, business_email, business_phone, business_address, logo_url, currency, date_format, invoice_prefix, default_due_days, default_tax_rate, default_template_id, whatsapp_enabled, whatsapp_api_key, whatsapp_message_template, created_at, updated_at
FROM settings
WHERE organisation_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, organisationID uuid.UUID) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings, organisationID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BusinessName,
		&i.BusinessEmail,
		&i.BusinessPhone,
		&i.BusinessAddress,
		&i.LogoUrl,
		&i.Currency,
		&i.DateFormat,
		&i.InvoicePrefix,
		&i.DefaultDueDays,
		&i.DefaultTaxRate,
		&i.DefaultTemplateID,
		&i.WhatsappEnabled,
		&i.WhatsappApiKey,
		&i.WhatsappMessageTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (
    organisation_id, business_name, business_email, business_phone, business_address, 
    logo_url, currency, date_format, invoice_prefix, default_due_days, 
    default_tax_rate, default_template_id, whatsapp_enabled, whatsapp_api_key, 
    whatsapp_message_template, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW()
)
ON CONFLICT (organisation_id)
DO UPDATE SET
    business_name = EXCLUDED.business_name,
    business_email = EXCLUDED.business_email,
    business_phone = EXCLUDED.business_phone,
    business_address = EXCLUDED.business_address,
    logo_url = EXCLUDED.logo_url,
    currency = EXCLUDED.currency,
    date_format = EXCLUDED.date_format,
    invoice_prefix = EXCLUDED.invoice_prefix,
    default_due_days = EXCLUDED.default_due_days,
    default_tax_rate = EXCLUDED.default_tax_rate,
    default_template_id = EXCLUDED.default_template_id,
    whatsapp_enabled = EXCLUDED.whatsapp_enabled,
    whatsapp_api_key = EXCLUDED.whatsapp_api_key,
    whatsapp_message_template = EXCLUDED.whatsapp_message_template,
    updated_at = NOW()
RETURNING id, organisation_id, business_name, business_email, business_phone, business_address, logo_url, currency, date_format, invoice_prefix, default_due_days, default_tax_rate, default_template_id, whatsapp_enabled, whatsapp_api_key, whatsapp_message_template, created_at, updated_at
`

type UpsertSettingsParams struct {
	OrganisationID          uuid.UUID      `json:"organisation_id"`
	BusinessName            *string        `json:"business_name"`
	BusinessEmail           *string        `json:"business_email"`
	BusinessPhone           *string        `json:"business_phone"`
	BusinessAddress         *string        `json:"business_address"`
	LogoUrl                 *string        `json:"logo_url"`
	Currency                string         `json:"currency"`
	DateFormat              string         `json:"date_format"`
	InvoicePrefix           string         `json:"invoice_prefix"`
	DefaultDueDays          int32          `json:"default_due_days"`
	DefaultTaxRate          pgtype.Numeric `json:"default_tax_rate"`
	DefaultTemplateID       pgtype.UUID    `json:"default_template_id"`
	WhatsappEnabled         bool           `json:"whatsapp_enabled"`
	WhatsappApiKey          *string        `json:"whatsapp_api_key"`
	WhatsappMessageTemplate string         `json:"whatsapp_message_template"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSettings,
		arg.OrganisationID,
		arg.BusinessName,
		arg.BusinessEmail,
		arg.BusinessPhone,
		arg.BusinessAddress,
		arg.LogoUrl,
		arg.Currency,
		arg.DateFormat,
		arg.InvoicePrefix,
		arg.DefaultDueDays,
		arg.DefaultTaxRate,
		arg.DefaultTemplateID,
		arg.WhatsappEnabled,
		arg.WhatsappApiKey,
		arg.WhatsappMessageTemplate,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BusinessName,
		&i.BusinessEmail,
		&i.BusinessPhone,
		&i.BusinessAddress,
		&i.LogoUrl,
		&i.Currency,
		&i.DateFormat,
		&i.InvoicePrefix,
		&i.DefaultDueDays,
		&i.DefaultTaxRate,
		&i.DefaultTemplateID,
		&i.WhatsappEnabled,
		&i.WhatsappApiKey,
		&i.WhatsappMessageTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
