// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package customersdb

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	ActorType      string             `json:"actor_type"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OldValue       []byte             `json:"old_value"`
	NewValue       []byte             `json:"new_value"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      *string            `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Name           string             `json:"name"`
	Email          *string            `json:"email"`
	Phone          *string            `json:"phone"`
	Address        *string            `json:"address"`
	TaxNumber      *string            `json:"tax_number"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ImpersonationSession struct {
	ID           uuid.UUID          `json:"id"`
	SuperAdminID uuid.UUID          `json:"super_admin_id"`
	TargetOrgID  uuid.UUID          `json:"target_org_id"`
	TargetUserID uuid.UUID          `json:"target_user_id"`
	Reason       string             `json:"reason"`
	TokenHash    string             `json:"token_hash"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	IpAddress    *netip.Addr        `json:"ip_address"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CustomerID     uuid.UUID          `json:"customer_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	Status         string             `json:"status"`
	IssuedDate     pgtype.Date        `json:"issued_date"`
	DueDate        pgtype.Date        `json:"due_date"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Total          pgtype.Numeric     `json:"total"`
	Currency       string             `json:"currency"`
	Notes          *string            `json:"notes"`
	Terms          *string            `json:"terms"`
	TemplateID     pgtype.UUID        `json:"template_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceItem struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	Description string             `json:"description"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	TaxRate     pgtype.Numeric     `json:"tax_rate"`
	TaxAmount   pgtype.Numeric     `json:"tax_amount"`
	LineTotal   pgtype.Numeric     `json:"line_total"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InvoiceSession struct {
	ID              uuid.UUID          `json:"id"`
	OrganisationID  uuid.UUID          `json:"organisation_id"`
	Year            int32              `json:"year"`
	Prefix          string             `json:"prefix"`
	CurrentSequence int32              `json:"current_sequence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Organisation struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Slug                  string             `json:"slug"`
	Email                 *string            `json:"email"`
	Phone                 *string            `json:"phone"`
	Address               *string            `json:"address"`
	LogoUrl               *string            `json:"logo_url"`
	Status                string             `json:"status"`
	CreatedBySuperAdminID pgtype.UUID        `json:"created_by_super_admin_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type OrganisationSubscription struct {
	ID                 uuid.UUID          `json:"id"`
	OrganisationID     uuid.UUID          `json:"organisation_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	ExternalID         *string            `json:"external_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Method         string             `json:"method"`
	Reference      *string            `json:"reference"`
	Notes          *string            `json:"notes"`
	PaymentDate    pgtype.Date        `json:"payment_date"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	PriceMonthly        pgtype.Numeric     `json:"price_monthly"`
	PriceYearly         pgtype.Numeric     `json:"price_yearly"`
	MaxUsers            int32              `json:"max_users"`
	MaxCustomers        int32              `json:"max_customers"`
	MaxInvoicesPerMonth int32              `json:"max_invoices_per_month"`
	MaxStorageMb        int32              `json:"max_storage_mb"`
	WhatsappEnabled     bool               `json:"whatsapp_enabled"`
	CustomTemplates     bool               `json:"custom_templates"`
	ApiAccess           bool               `json:"api_access"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	IsSystem       bool               `json:"is_system"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	TaxRate        pgtype.Numeric     `json:"tax_rate"`
	Unit           string             `json:"unit"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Setting struct {
	ID                      uuid.UUID          `json:"id"`
	OrganisationID          uuid.UUID          `json:"organisation_id"`
	BusinessName            *string            `json:"business_name"`
	BusinessEmail           *string            `json:"business_email"`
	BusinessPhone           *string            `json:"business_phone"`
	BusinessAddress         *string            `json:"business_address"`
	LogoUrl                 *string            `json:"logo_url"`
	Currency                string             `json:"currency"`
	DateFormat              string             `json:"date_format"`
	InvoicePrefix           string             `json:"invoice_prefix"`
	DefaultDueDays          int32              `json:"default_due_days"`
	DefaultTaxRate          pgtype.Numeric     `json:"default_tax_rate"`
	DefaultTemplateID       pgtype.UUID        `json:"default_template_id"`
	WhatsappEnabled         bool               `json:"whatsapp_enabled"`
	WhatsappApiKey          *string            `json:"whatsapp_api_key"`
	WhatsappMessageTemplate string             `json:"whatsapp_message_template"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SuperAdmin struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SuperAuditLog struct {
	ID           uuid.UUID          `json:"id"`
	SuperAdminID pgtype.UUID        `json:"super_admin_id"`
	Action       string             `json:"action"`
	TargetType   *string            `json:"target_type"`
	TargetID     pgtype.UUID        `json:"target_id"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SuperRefreshToken struct {
	ID           uuid.UUID          `json:"id"`
	SuperAdminID uuid.UUID          `json:"super_admin_id"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Name           string             `json:"name"`
	HtmlContent    string             `json:"html_content"`
	IsDefault      bool               `json:"is_default"`
	ThumbnailUrl   *string            `json:"thumbnail_url"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RoleID         pgtype.UUID        `json:"role_id"`
}

type WhatsappLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	RecipientPhone string             `json:"recipient_phone"`
	Message        string             `json:"message"`
	Status         string             `json:"status"`
	ErrorMessage   *string            `json:"error_message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
