// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package customersdb

import (
	"context"

	"github.com/google/uuid"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*)
FROM customers
WHERE organisation_id = $1
AND (
    $2::TEXT = '' OR 
    name ILIKE '%' || $2 || '%' OR 
    email ILIKE '%' || $2 || '%' OR 
    phone ILIKE '%' || $2 || '%'
)
`

type CountCustomersParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Search         string    `json:"search"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.OrganisationID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    organisation_id, name, email, phone, address, tax_number, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, organisation_id, name, email, phone, address, tax_number, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           string    `json:"name"`
	Email          *string   `json:"email"`
	Phone          *string   `json:"phone"`
	Address        *string   `json:"address"`
	TaxNumber      *string   `json:"tax_number"`
	IsActive       bool      `json:"is_active"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OrganisationID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.TaxNumber,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1 AND organisation_id = $2
`

type DeleteCustomerParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.OrganisationID)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, organisation_id, name, email, phone, address, tax_number, is_active, created_at, updated_at
FROM customers
WHERE id = $1 AND organisation_id = $2
`

type GetCustomerByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.OrganisationID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT id, organisation_id, name, email, phone, address, tax_number, is_active, created_at, updated_at
FROM customers
WHERE organisation_id = $1
AND (
    $2::TEXT = '' OR 
    name ILIKE '%' || $2 || '%' OR 
    email ILIKE '%' || $2 || '%' OR 
    phone ILIKE '%' || $2 || '%'
)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type GetCustomersParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Search         string    `json:"search"`
	Offset         int32     `json:"offset"`
	PerPage        int32     `json:"per_page"`
}

func (q *Queries) GetCustomers(ctx context.Context, arg GetCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getCustomers,
		arg.OrganisationID,
		arg.Search,
		arg.Offset,
		arg.PerPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.TaxNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    name = COALESCE($3, name),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    address = COALESCE($6, address),
    tax_number = COALESCE($7, tax_number),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, name, email, phone, address, tax_number, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	Name           *string   `json:"name"`
	Email          *string   `json:"email"`
	Phone          *string   `json:"phone"`
	Address        *string   `json:"address"`
	TaxNumber      *string   `json:"tax_number"`
	IsActive       *bool     `json:"is_active"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.TaxNumber,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
