// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package invoicesessionsdb

import (
	"context"

	"github.com/google/uuid"
)

const createInvoiceSession = `-- name: CreateInvoiceSession :one
INSERT INTO invoice_sessions (
    organisation_id, year, prefix, current_sequence, created_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, organisation_id, year, prefix, current_sequence, created_at
`

type CreateInvoiceSessionParams struct {
	OrganisationID  uuid.UUID `json:"organisation_id"`
	Year            int32     `json:"year"`
	Prefix          string    `json:"prefix"`
	CurrentSequence int32     `json:"current_sequence"`
}

func (q *Queries) CreateInvoiceSession(ctx context.Context, arg CreateInvoiceSessionParams) (InvoiceSession, error) {
	row := q.db.QueryRow(ctx, createInvoiceSession,
		arg.OrganisationID,
		arg.Year,
		arg.Prefix,
		arg.CurrentSequence,
	)
	var i InvoiceSession
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Year,
		&i.Prefix,
		&i.CurrentSequence,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceSessionByID = `-- name: GetInvoiceSessionByID :one
SELECT id, organisation_id, year, prefix, current_sequence, created_at
FROM invoice_sessions
WHERE id = $1 AND organisation_id = $2
`

type GetInvoiceSessionByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetInvoiceSessionByID(ctx context.Context, arg GetInvoiceSessionByIDParams) (InvoiceSession, error) {
	row := q.db.QueryRow(ctx, getInvoiceSessionByID, arg.ID, arg.OrganisationID)
	var i InvoiceSession
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Year,
		&i.Prefix,
		&i.CurrentSequence,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceSessions = `-- name: GetInvoiceSessions :many
SELECT id, organisation_id, year, prefix, current_sequence, created_at
FROM invoice_sessions
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvoiceSessions(ctx context.Context, organisationID uuid.UUID) ([]InvoiceSession, error) {
	rows, err := q.db.Query(ctx, getInvoiceSessions, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceSession
	for rows.Next() {
		var i InvoiceSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Year,
			&i.Prefix,
			&i.CurrentSequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceSessionSequence = `-- name: UpdateInvoiceSessionSequence :one
UPDATE invoice_sessions
SET current_sequence = current_sequence + 1
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, year, prefix, current_sequence, created_at
`

type UpdateInvoiceSessionSequenceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) UpdateInvoiceSessionSequence(ctx context.Context, arg UpdateInvoiceSessionSequenceParams) (InvoiceSession, error) {
	row := q.db.QueryRow(ctx, updateInvoiceSessionSequence, arg.ID, arg.OrganisationID)
	var i InvoiceSession
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Year,
		&i.Prefix,
		&i.CurrentSequence,
		&i.CreatedAt,
	)
	return i, err
}
